BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[UserPreference] (
    [id] INT NOT NULL IDENTITY(1,1),
    [userId] INT NOT NULL,
    [preferences] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [UserPreference_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [UserPreference_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [UserPreference_userId_key] UNIQUE NONCLUSTERED ([userId])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
